### ISSUE TITLE
首页有js错误：Uncaught Error: Invalid dimensions for plot, width = null, height = null

### ISSUE THREAD

**Issue by flysec** [RayeWang/easyadmin#12]
修改方法：加上piechart-placeholder和sales-charts两个div，如下：

                       <div class="tab-content">
			      <div role="tabpanel" class="tab-pane active" id="Index">
								欢迎使用EasyAdmin
                                    <div id="piechart-placeholder"></div>
                                    <div id="sales-charts"></div>
			      </div>

			</div>

**Comment by RayeWang** [comment]
谢谢，已调整
